backend:
  name: github
  repo: bahung1221/bahung1221.github.io
  branch: gh-pages
  site_domain: heuristic-bose-56dfb0.netlify.com

media_folder: "assets/img/upload"

publish_mode: editorial_workflow

preview: false

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modified Date", name: "modified", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tag", name: "tag", multiple: true, widget: "relation", collection: "relation", file: "tags", search_fields: ["tags.*.title"], value_field: "tags.*.title"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Keywords", name: "keywords", multiple: true, widget: "list", field: {label: Title, name: title}, max: 20, minimize_collapsed: true, collapsed: true, allow_add: true}

  - name: "external_posts"
    label: "External Posts"
    folder: "_external_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "external_post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Crawl Date", name: "crawl_date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tag", name: "tag", multiple: true, required: false, widget: "relation", collection: "relation", file: "external_tags", search_fields: ["external_tags.*.title"], value_field: "external_tags.*.title"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Blog", name: "blog", widget: "string"}
      - {label: "Original URL", name: "original_url", widget: "string"}
      - {label: "Original Publish Date", name: "original_publish_date", widget: "datetime"}

  - name: "relation"
    label: "Relation"
    files:
      - label: "Tags"
        name: "tags"
        file: "_relation/tags.yml"
        fields:
          - label: Tags
            name: tags
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown, required: false}
      - label: "External Tags"
        name: "external_tags"
        file: "_relation/external_tags.yml"
        fields:
          - label: Tags
            name: external_tags
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown, required: false}
